services:

  haste-server:
    build: .
    container_name: haste-server
    restart: always
    environment:
      - STORAGE_TYPE=memcached
      - STORAGE_HOST=memcached
      - STORAGE_PORT=11211
    ports:
      - "7777:7777"

  memcached:
    image: memcached:latest
    restart: always
